# Generated by Django 6.0.8 on 2026-08-25 17:24

import django.db.models.deletion
from django.db import migrations, models

import integrations.fields.encrypted
import integrations.models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="credential",
            name="config",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Configuration"
            ),
        ),
        migrations.AddField(
            model_name="credential",
            name="integration",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Integration"
            ),
        ),
        migrations.AddField(
            model_name="credential",
            name="secrets",
            field=integrations.fields.encrypted.EncryptedJSONField(
                blank=True, default=dict, verbose_name="Secrets"
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="site",
            field=models.ForeignKey(
                default=integrations.models.set_default_site_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credentials",
                to="sites.site",
                verbose_name="Site",
            ),
        ),
        migrations.AddConstraint(
            model_name="credential",
            constraint=models.UniqueConstraint(
                fields=("site", "integration"), name="unique_site_integration"
            ),
        ),
    ]
