# Generated by Django 6.0.8 on 2026-08-25 14:33

from django.db import migrations, models

import integrations.encrypted_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DummyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "secret",
                    integrations.encrypted_fields.EncryptedTextField(
                        blank=True, null=True
                    ),
                ),
            ],
        ),
    ]
