# Generated by Django 6.0.8 on 2026-08-25 17:24

from django.db import migrations, models

import integrations.fields.encrypted


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DummyJSONModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    integrations.fields.encrypted.EncryptedJSONField(default=dict),
                ),
            ],
        ),
    ]
